services:
  browserless:
    image: ghcr.io/browserless/chrome:v2.6.1
    environment:
      TZ: America/Sao_Paulo
      CONCURRENT: ${BROWSERLESS_CONCURRENT}
      TIMEOUT: ${BROWSERLESS_TIMEOUT}
      QUEUED: ${BROWSERLESS_QUEUED}
    ports:
      - ${BROWSERLESS_DOCKER_PORT}:3000
  redis:
    image: redis
    environment:
      TZ: America/Sao_Paulo
    command:
      - redis-server
      - --save 60 1
      - --loglevel warning
      - --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_DOCKER_PORT}:6379
    volumes:
      - "./docker/redis:/data"
  rq-dashboard:
    build: https://github.com/Parallels/rq-dashboard.git
    ports:
      - ${RQ_DASHBOARD_DOCKER_PORT}:9181
    environment:
      RQ_DASHBOARD_REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379
    depends_on:
      - redis
  resource-hunter:
    build: .
    env_file:
      - .env
      - .env.docker
    command: make docker-entry-resource-hunter
    depends_on:
      - redis
  worker:
    build: .
    env_file:
      - .env
      - .env.docker
    command: make docker-entry-worker
    depends_on:
      - browserless
      - redis
  api:
    build: .
    env_file:
      - .env
      - .env.docker
    command: make docker-entry-api
    ports:
      - ${API_DOCKER_PORT}:${API_PORT}
    depends_on:
      - redis
  discord-bot:
    build: .
    env_file:
      - .env
      - .env.docker
    command: make docker-entry-discord-bot
    depends_on:
      - redis
