services:
  browserless:
    image: ghcr.io/browserless/chrome:v2.6.1
    environment:
      TZ: America/Sao_Paulo
      CONCURRENT: ${BROWSERLESS_CONCURRENT}
      TIMEOUT: ${BROWSERLESS_TIMEOUT}
      QUEUED: ${BROWSERLESS_QUEUED}
    ports:
      - 127.0.0.1:33000:3000
  redis:
    image: redis
    environment:
      TZ: America/Sao_Paulo
    command:
      - redis-server
      - --save 60 1
      - --loglevel warning
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - "./docker/redis:/data"
  api:
    build: .
    env_file: .env
    environment:
      APP_PW_WS_ENDPOINT: ws://browserless:3000/chrome/playwright
      APP_REDIS_URL: redis://redis:6379
    command: make docker-entry-api
    ports:
      - 127.0.0.1:${API_PORT}:9000
    depends_on:
      - redis
