services:
  browserless:
    image: ghcr.io/browserless/chrome:v2.6.1
    environment:
      TZ: America/Sao_Paulo
      CONCURRENT: ${BROWSERLESS_CONCURRENT}
      TIMEOUT: ${BROWSERLESS_TIMEOUT}
      QUEUED: ${BROWSERLESS_QUEUED}
    ports:
      - 127.0.0.1:33000:3000
  redis:
    image: redis
    environment:
      TZ: America/Sao_Paulo
    command:
      - redis-server
      - --save 60 1
      - --loglevel warning
      - --requirepass ${REDIS_PASSWORD}
    ports:
      - 0.0.0.0:36379:6379
    volumes:
      - "./docker/redis:/data"
  resource-hunter:
    build: .
    env_file: .env.docker
    command: make docker-entry-resource-hunter
    depends_on:
      - browserless
      - redis
  api:
    build: .
    env_file: .env.docker
    command: make docker-entry-api
    ports:
      - 127.0.0.1:${API_PORT}:9000
    depends_on:
      - redis
