version: '3'
services:
  browserless:
    image: browserless/chrome
    environment:
      MAX_CONCURRENT_SESSIONS: 5
      CONNECTION_TIMEOUT: -1
      MAX_QUEUE_LENGTH: 4995
      PREBOOT_CHROME: true
      KEEP_ALIVE: true
      DEFAULT_STEALTH: true
      DEFAULT_HEADLESS: true
    ports:
      - 33000:3000
  redis:
    image: redis
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - 6379:6379
    volumes:
      - "./docker/redis:/data"
  workers:
    build: .
    environment:
      REDIS_HOST: redis
      REDIS_DEFAULT_TTL: -1
      BROWSERLESS_URL: ws://browserless:3000
    command: [ "make", "start-rq-worker", "workers=8" ]
    depends_on:
      - browserless
      - redis
  api:
    build: .
    environment:
      REDIS_HOST: redis
      REDIS_DEFAULT_TTL: -1
      BROWSERLESS_URL: ws://browserless:3000
    ports:
      - 9000:9000
    depends_on:
      - workers