version: '3'
services:
  browserless:
    image: browserless/chrome
    environment:
      MAX_CONCURRENT_SESSIONS: ${BROWSERLESS_MAX_CONCURRENT_SESSIONS}
      CONNECTION_TIMEOUT: -1
      DEFAULT_STEALTH: true
      DEFAULT_HEADLESS: true
    ports:
      - 33000:3000
  redis:
    image: redis
    command:
      - redis-server
      - --save 60 1
      - --loglevel warning
    ports:
      - 6379:6379
    volumes:
      - "./docker/redis:/data"
  worker:
    build: .
    env_file: .env
    environment:
      APP_BROWSERLESS_CDP_ENDPOINT_URL: ws://browserless:3000
      APP_REDIS_HOST: redis
    command: make docker-entry-worker
    depends_on:
      - browserless
  api:
    build: .
    env_file: .env
    environment:
      APP_BROWSERLESS_CDP_ENDPOINT_URL: ws://browserless:3000
      APP_REDIS_HOST: redis
    command: make docker-entry-api
    ports:
      - ${API_PORT}:9000
    depends_on:
      - worker