services:
  browserless:
    image: ghcr.io/browserless/chrome:latest
    # build:
    #   context: https://github.com/browserless/browserless.git#v2.6.1
    #   dockerfile: docker/chrome/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      CONCURRENT: ${BROWSERLESS_CONCURRENT}
      TIMEOUT: 0
      QUEUED: 0
    ports:
      - 127.0.0.1:33000:3000
  redis:
    image: redis
    environment:
      TZ: America/Sao_Paulo
    command:
      - redis-server
      - --save 60 1
      - --loglevel warning
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - "./docker/redis:/data"
  rq-dashboard:
    build: https://github.com/Parallels/rq-dashboard.git
    environment:
      RQ_DASHBOARD_REDIS_URL: redis://redis:6379
      RQ_DASHBOARD_USERNAME: ${RQ_DASHBOARD_USERNAME}
      RQ_DASHBOARD_PASSWORD: ${RQ_DASHBOARD_PASSWORD}
    ports:
      - 127.0.0.1:9181:9181
    depends_on:
      - redis
  worker:
    build: .
    env_file: .env
    environment:
      APP_PW_CDP_ENDPOINT_URL: ws://browserless:3000/chrome/playwright
      APP_REDIS_URL: redis://redis:6379
    command: make docker-entry-worker
    depends_on:
      - browserless
      - redis
  api:
    build: .
    env_file: .env
    environment:
      APP_PW_CDP_ENDPOINT_URL: ws://browserless:3000/chrome/playwright
      APP_REDIS_URL: redis://redis:6379
    command: make docker-entry-api
    ports:
      - 127.0.0.1:${API_PORT}:9000
    depends_on:
      - worker
      - redis
