version: '3'
services:
  browserless:
    image: browserless/chrome
    environment:
      MAX_CONCURRENT_SESSIONS: 4
      CONNECTION_TIMEOUT: -1
      MAX_QUEUE_LENGTH: 4995
      PREBOOT_CHROME: true
      KEEP_ALIVE: true
      DEFAULT_STEALTH: true
      DEFAULT_HEADLESS: true
    ports:
      - 33000:3000
  redis:
    image: redis
    command:
      - redis-server
      - --save 60 1
      - --loglevel warning
    ports:
      - 6379:6379
    volumes:
      - "./docker/redis:/data"
  worker:
    build: .
    env_file: .env.docker
    command: docker-entry-worker workers=4
    depends_on:
      - browserless
  api:
    build: .
    env_file: .env.docker
    command: docker-entry-api
    ports:
      - 9000:9000
    depends_on:
      - worker