import os

CONCURRENCY = int(os.getenv("APP_CONCURRENCY", 1))
REDIS_URL = os.getenv("APP_REDIS_URL")
PW_WS_ENDPOINT = os.getenv("APP_PW_WS_ENDPOINT")
PW_DEFAULT_TIMEOUT = int(os.getenv("APP_PW_DEFAULT_TIMEOUT", 60000))  # 1 minute
PW_PROXY_ENABLED = bool(int(os.getenv("APP_PW_PROXY_ENABLED", 0)))
WEBSHARE_TOKEN = os.getenv("APP_WEBSHARE_TOKEN")
DISCORD_BOT_TOKEN = os.getenv("APP_DISCORD_BOT_TOKEN")

try:
    DISCORD_BOT_GUILD_ID = int(os.getenv("APP_DISCORD_BOT_GUILD_ID"))
except Exception:
    DISCORD_BOT_GUILD_ID = None

try:
    DISCORD_BOT_TRACK_TREES_CHANNEL_ID = int(os.getenv("APP_DISCORD_BOT_TRACK_TREES_CHANNEL_ID"))
except Exception:
    DISCORD_BOT_TRACK_TREES_CHANNEL_ID = None

try:
    DISCORD_BOT_TRACK_INDUSTRIES_CHANNEL_ID = int(
        os.getenv("APP_DISCORD_BOT_TRACK_INDUSTRIES_CHANNEL_ID")
    )
except Exception:
    DISCORD_BOT_TRACK_INDUSTRIES_CHANNEL_ID = None
