import os

REDIS_HOST = os.getenv("REDIS_HOST", "localhost")
REDIS_PORT = os.getenv("REDIS_PORT", 6379)
REDIS_DEFAULT_TTL = os.getenv("REDIS_DEFAULT_TTL", 10)
BROWSERLESS_URL = os.getenv("BROWSERLESS_URL", "ws://localhost:33000")
BROWSERLESS_DEFAULT_TIMEOUT = os.getenv("BROWSERLESS_DEFAULT_TIMEOUT", 60000 * 15)
